# The URL the site will be built for
base_url = "https://efe.dev"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

theme = "anemone"

generate_feeds = true

feed_filenames = ["rss.xml"]

taxonomies = [
    {name = "tags", feed = true, paginate_by = 10},
]

[markdown]
render_emoji = true
external_links_target_blank = true
smart_punctuation = true

[markdown.highlighting]
dark_theme = "material-theme-palenight"
light_theme = "everforest-light"

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[link_checker]
internal_level = "warn"

[extra]
author = "Efe Karasakal"
favicon = "favicon.ico"
list_pages = false
enable_search = true

## Navigation
header_nav = [
  { url = "/", name_en = "/home/" },
  { url = "/rss.xml", name_en = "/rss/" },
##  { url = "/journal", name_en = "/journal/" },
  { url = "/blog", name_en = "/blog/" },
  { url = "/projects", name_en = "/projects/" }
]
